apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
        - name: weatherapi
          image: ghcr.io/woosung142/weather-k3s/weatherapi:main
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: api-secret
      imagePullSecrets:
        - name: ghcr-secret
          volumeMounts:
          - name: tz-seoul
            mountPath: /etc/localtime
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul