apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: ghcr.io/woosung142/weather-k3s/weatherapi
    newTag: main-f129e16
  - name: ghcr.io/woosung142/weather-k3s/cctvapi
    newTag: main-20d34cb
