apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weatherapi-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: www.weapi.shop
      http:
        paths:
          - path: /api/weather
            pathType: Prefix
            backend:
              service:
                name: weatherapi-service
                port:
                  number: 80