apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weatherapi-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"  
spec:
  rules:
    - host: www.weapi.shop
      http:
        paths:
          - path: /api/weather
            pathType: Prefix
            backend:
              service:
                name: weatherapi-service
                port:
                  number: 80
          - path: /get_cctv
            pathType: Prefix
            backend:
              service:
                name: cctvapi-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weatherapi-service
                port:
                  number: 80