controller:
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      cpu: 30m
      memory: 512Mi

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: "argocd.weapi.shop"
    path: /
    pathType: Prefix 
  resources:
    requests:
      cpu: 3m
      memory: 40Mi
    limits:
      cpu: 9m
      memory: 80Mi

repoServer: #메모리 피크 보여서 메모리 리밋 3배 줌
  replicas: 1
  resources:
    requests:
      cpu: 2m
      memory: 40Mi
    limits:
      cpu: 6m
      memory: 120Mi

applicationSet:
  replicas: 0

redis:
  resources:
    requests:
      cpu: 6m
      memory: 6Mi
    limits:
      cpu: 12m
      memory: 12Mi
dex:
  enabled: false  # SSO 비활성화
notifications:
  enabled: false  # 알림 비활성화

configs:
  cm:
    kustomize.buildOptions: --enable-helm