controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m #10m
      memory: 250Mi
    limits:
      cpu: 300m #30m
      memory: 512Mi

server:
  replicas: 1
  extraArgs:
    - --insecure  # HTTPS 비활성화 1번
  ingress:
    enabled: false
#    ingressClassName: traefik
#    hostname: "argocd.weapi.shop"
#    tls: false

#    extraPaths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: argocd-server
#            port:
#              number: 80
#  service:
#    annotations:
#      annotations:
#        traefik.ingress.kubernetes.io/service.serversscheme: http # HTTPS 비활성화 2번
  resources:
    requests:
      cpu: 3m
      memory: 40Mi
    limits:
      cpu: 9m
      memory: 80Mi

repoServer: #메모리 피크 보여서 메모리 리밋 3배 줌
  replicas: 1
  resources:
    requests:
      cpu: 50m #2m
      memory: 120Mi #40Mi
    limits:
      cpu: 200m #6m
      memory: 360Mi #120Mi

applicationSet:
  replicas: 0

redis:
  resources:
    requests:
      cpu: 6m
      memory: 6Mi
    limits:
      cpu: 12m
      memory: 12Mi
dex:
  enabled: false  # SSO 비활성화
notifications:
  enabled: false  # 알림 비활성화

configs:
  cm:
    kustomize.buildOptions: --enable-helm